### ISSUE TITLE
Add support for java 16+

### ISSUE THREAD

**Issue by Emibergo02** [Exlll/ConfigLib#18]
Many servers use 1.16.X and if you downgrade your jdk to java 16 
would allow many devs to have ConfigLib (which is the best config lib on spigot)
on their plugins without impacting performance so much

**Comment by Exlll** [comment]
Hi, 

thanks for the suggestion. This library uses Java 17 features (like `sealed` interfaces) at multiple places which is why downgrading to Java 16 would some rework.

According to the [Oracle Java SE Support Roadmap](https://www.oracle.com/java/technologies/java-se-support-roadmap.html) Java 16 is also deprecated and has been superseded by Java 17 for a while now. Java 17 is an LTS version, is supported until 2026, and includes the latest security fixes. I'd suggest upgrading to it as I don't see a reason why the upgrade is not possible. Minecraft version 1.16.x is not tied to Java 16. 

Have you tried upgrading to Java 17 and have you encountered any problems with your Minecraft 1.16.x server by doing so?

**Comment by Exlll** [comment]
I'm closing this issue as there were no further replies from its creator. It seems like they added support for Java 16 in their own fork.

**Comment by Emibergo02** [comment]
i din't see your answer. i'm really sorry.
anyway here is my Java 16 version of ConfigLib perfectly working and actually used by many of my 1.16 plugins
[https://github.com/Emibergo02/ConfigLib](https://github.com/Emibergo02/ConfigLib)

**Comment by Emibergo02** [comment]
Anyway "Minecraft version 1.16.x is not tied to Java 16" is not correct.
1.16.x is tied to java 16. 
From 1.17.x minecraft server supports java 17

**Comment by Exlll** [comment]
> Anyway "Minecraft version 1.16.x is not tied to Java 16" is not correct.

You are right, sorry, I updated my previous comment.
