### ISSUE TITLE
Achieve cross-version support by making the library compatible with Java 8

### ISSUE THREAD

**Issue by DavidTheExplorer** [Exlll/ConfigLib#22]
Hello, I'm trying to use the library in a plugin that must offer 1.8 support - so I always compiled it on Java 8.
Now the compiler yells about `cannot access de.exlll.configlib.ConfigLib class file has wrong version 61.0, should be 52.0`.

**Comment by Exlll** [comment]
Hey,

this library uses and supports features that have only become available in later Java versions, e.g. records and sealed interfaces. While it is possible to create a version of this library that doesn't use these, I'd prefer not having to rewrite a bunch of classes and then having to maintain two separate versions, considering that [Java 8 support basically ended last year](https://www.oracle.com/java/technologies/java-se-support-roadmap.html).

If you'd like to create your own fork to add Java 8 support, a good starting point is to delete all the tests and all the classes that deal with Java records.

**Comment by DavidTheExplorer** [comment]
Realistically Java 8 will last for years to come, especially on the minecraft environment.

Also why would you need to maintain 2 separate versions if Java is backwards compatible?
I'm not a Java 17 expert, so if you can elaborate that would be awesome.

**Comment by Exlll** [comment]
If I understood your problem correctly, you need a version of this library that compiles with Java 8, is that right? For this library to compile with Java 8, all features and methods that were added in later Java versions need to be either removed from the codebase or somehow externalized so that they are only compiled conditionally. For example, all classes that have something to do with serializing Java records (that were only added in Java 16) to YAML, would have to be rewritten. Since I'm not willing to simply drop support for Java records, I would have to maintain two separate versions of those classes, e.g. one version with and one without support for records.

**Comment by DavidTheExplorer** [comment]
I understand, can I ask why you are not willing to give up using recrods? Not trying to be rude, I'm just really curious because this library has a lot of potential - so using it on all spigot versions would be awesome.

**Comment by Exlll** [comment]
Sorry, I'm not willing to accept such a PR. I'm using records in my own configurations and know two other people who also do. I assume that some other users of this library also use records and would like to continue to do so; they just make writing configurations faster, and at the same time more readable, at least for me. 

To be honest, I'd also rather spent my time implementing new features instead of removing old ones, especially since we are talking about support an almost ten year old Java version. Newer versions of [Spigot](https://www.spigotmc.org/wiki/buildtools/#prerequisites) and [Paper](https://docs.papermc.io/paper/getting-started) already require use of Java 17+. If I remember correctly, even Mojang moved away from Java 8.

Records are also not the only (but besides the documentation by far the most prevalent) thing that needs to changed. If you want to give it a try, checkout the code, change the Java version in the [`core-config.gradle.kts`](https://github.com/Exlll/ConfigLib/blob/master/buildSrc/src/main/kotlin/core-config.gradle.kts) file, and try to compile the code using the Gradle `build` task. Doing so should show you which files need to be changed. As I wrote earlier, you should probably first delete all the tests since they will not compile, for sure. 

If you really go through that, I can imagine that it could be helpful for people who rely on Java 8 if you were to upload that version to your own fork.
