### ISSUE TITLE
Will comments be added in lists/maps etc?

### ISSUE THREAD

**Issue by KweezyCode** [Exlll/ConfigLib#32]
found that it is not supported by library, so read title

**Comment by Exlll** [comment]
This will probably not be supported in the foreseeable future. Sadly, all YAML parsers (for Java) that I tested when I started writing this library had either too many bugs and problems or did not support comments. Maybe the situation has changed now but testing these libraries takes quite some time and the code in this library also needs to be updated. 

The code I've written to support comments feels pretty hacky to me although it seems to work quite well since no major problems have been reported so far. However, when you start working on comment support for collections all kinds of edge cases start to pop up, especially when it comes to nested collections (e.g., `List<Map<String, Set<...>>>`). I'd rather wait for some library to properly support these cases than write more hacky code myself. 

In any case, the usual workaround is to add the comment to the list itself and describe the structure of its elements there.

**Comment by KweezyCode** [comment]
this library is actually more stable than the others in handling comments that I tried (java-serializer, AnnotationConfig, night-config). It's a shame that comment support is so limited in parsers. In any case, thanks for your work! Your library works fine (POJO + Annotated fields)
